@startuml Test Sequence

!theme merkleblue from https://raw.githubusercontent.com/gjermath/diagramming/main/plantuml/themes

actor Alice

Alice -> Bob: Authentication Request
Bob -> RequestHandler: validated Authenticated Request
RequestHandler --> Bob: Authenticated Response (OK)
Bob --> Alice: Authentication Response (OK)

'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml